### ISSUE TITLE
The `love.graphics.print` doesn't do anything at all

### ISSUE THREAD

**Issue by Mwalters75** [HTV04/wiilove#3]
I ran the following script:
```lua
function love.load()
    love.graphics.setColor(255, 255, 255)
end

function love.draw()
    love.graphics.print("Hello World!", 0, 0)
end
```
And all it showed was a blank screen, so I thought that it was too into the center, so I moved it down a little, and nothing happened. I think it's because I didn't call the functions... And the above functions only worked on LOVE.

**Comment by HTV04** [comment]
Try moving the text lower, FreeTypeGX renders fonts above the set Y value for some reason. I'm going to try to fix it after I work on adding support for more textures

**Comment by Mwalters75** [comment]
So, would -100 work well enough?

**Comment by Mwalters75** [comment]
OK.

**Comment by HTV04** [comment]
Did that work for you?

**Comment by Mwalters75** [comment]
It worked, but the characters were peeking out from the top, so I just changed it to 100 to be a little bit more better.
